// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.0
// source: db/vr/message.proto

package vr

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ShardOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard *uint32 `protobuf:"varint,1,req,name=shard" json:"shard,omitempty"`
	Op    []byte  `protobuf:"bytes,2,req,name=op" json:"op,omitempty"`
}

func (x *ShardOp) Reset() {
	*x = ShardOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardOp) ProtoMessage() {}

func (x *ShardOp) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardOp.ProtoReflect.Descriptor instead.
func (*ShardOp) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{0}
}

func (x *ShardOp) GetShard() uint32 {
	if x != nil && x.Shard != nil {
		return *x.Shard
	}
	return 0
}

func (x *ShardOp) GetOp() []byte {
	if x != nil {
		return x.Op
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op          []byte     `protobuf:"bytes,1,req,name=op" json:"op,omitempty"`
	Clientid    *uint64    `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Clientreqid *uint64    `protobuf:"varint,3,req,name=clientreqid" json:"clientreqid,omitempty"`
	Ops         []*ShardOp `protobuf:"bytes,4,rep,name=ops" json:"ops,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetOp() []byte {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Request) GetClientid() uint64 {
	if x != nil && x.Clientid != nil {
		return *x.Clientid
	}
	return 0
}

func (x *Request) GetClientreqid() uint64 {
	if x != nil && x.Clientreqid != nil {
		return *x.Clientreqid
	}
	return 0
}

func (x *Request) GetOps() []*ShardOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type UnloggedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op          []byte  `protobuf:"bytes,1,req,name=op" json:"op,omitempty"`
	Clientid    *uint64 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Clientreqid *uint64 `protobuf:"varint,3,req,name=clientreqid" json:"clientreqid,omitempty"`
}

func (x *UnloggedRequest) Reset() {
	*x = UnloggedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloggedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloggedRequest) ProtoMessage() {}

func (x *UnloggedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloggedRequest.ProtoReflect.Descriptor instead.
func (*UnloggedRequest) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{2}
}

func (x *UnloggedRequest) GetOp() []byte {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *UnloggedRequest) GetClientid() uint64 {
	if x != nil && x.Clientid != nil {
		return *x.Clientid
	}
	return 0
}

func (x *UnloggedRequest) GetClientreqid() uint64 {
	if x != nil && x.Clientreqid != nil {
		return *x.Clientreqid
	}
	return 0
}

type RequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *Request `protobuf:"bytes,1,req,name=req" json:"req,omitempty"`
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{3}
}

func (x *RequestMessage) GetReq() *Request {
	if x != nil {
		return x.Req
	}
	return nil
}

type UnloggedRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *UnloggedRequest `protobuf:"bytes,1,req,name=req" json:"req,omitempty"`
}

func (x *UnloggedRequestMessage) Reset() {
	*x = UnloggedRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloggedRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloggedRequestMessage) ProtoMessage() {}

func (x *UnloggedRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloggedRequestMessage.ProtoReflect.Descriptor instead.
func (*UnloggedRequestMessage) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnloggedRequestMessage) GetReq() *UnloggedRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type ReplyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View        *uint64 `protobuf:"varint,1,req,name=view" json:"view,omitempty"`
	Opnum       *uint64 `protobuf:"varint,2,req,name=opnum" json:"opnum,omitempty"`
	Reply       []byte  `protobuf:"bytes,3,req,name=reply" json:"reply,omitempty"`
	Clientreqid *uint64 `protobuf:"varint,4,req,name=clientreqid" json:"clientreqid,omitempty"`
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_vr_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_db_vr_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_db_vr_message_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyMessage) GetView() uint64 {
	if x != nil && x.View != nil {
		return *x.View
	}
	return 0
}

func (x *ReplyMessage) GetOpnum() uint64 {
	if x != nil && x.Opnum != nil {
		return *x.Opnum
	}
	return 0
}

func (x *ReplyMessage) GetReply() []byte {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *ReplyMessage) GetClientreqid() uint64 {
	if x != nil && x.Clientreqid != nil {
		return *x.Clientreqid
	}
	return 0
}

var File_db_vr_message_proto protoreflect.FileDescriptor

var file_db_vr_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x62, 0x2f, 0x76, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x72, 0x22, 0x2f, 0x0a, 0x07, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x4f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x76, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x71, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x72, 0x65,
	0x71, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x76, 0x72, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x52, 0x03, 0x6f,
	0x70, 0x73, 0x22, 0x5f, 0x0a, 0x0f, 0x55, 0x6e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x71, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x72, 0x65,
	0x71, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x03, 0x72, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x16, 0x55, 0x6e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25,
	0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x72,
	0x2e, 0x55, 0x6e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x70, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x70, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x70, 0x6e, 0x75, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x72,
	0x65, 0x71, 0x69, 0x64, 0x18, 0x04, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x72, 0x65, 0x71, 0x69, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x61, 0x70, 0x2f, 0x67, 0x6f,
	0x2d, 0x79, 0x63, 0x73, 0x62, 0x2f, 0x64, 0x62, 0x2f, 0x76, 0x72,
}

var (
	file_db_vr_message_proto_rawDescOnce sync.Once
	file_db_vr_message_proto_rawDescData = file_db_vr_message_proto_rawDesc
)

func file_db_vr_message_proto_rawDescGZIP() []byte {
	file_db_vr_message_proto_rawDescOnce.Do(func() {
		file_db_vr_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_vr_message_proto_rawDescData)
	})
	return file_db_vr_message_proto_rawDescData
}

var file_db_vr_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_db_vr_message_proto_goTypes = []interface{}{
	(*ShardOp)(nil),                // 0: vr.ShardOp
	(*Request)(nil),                // 1: vr.Request
	(*UnloggedRequest)(nil),        // 2: vr.UnloggedRequest
	(*RequestMessage)(nil),         // 3: vr.RequestMessage
	(*UnloggedRequestMessage)(nil), // 4: vr.UnloggedRequestMessage
	(*ReplyMessage)(nil),           // 5: vr.ReplyMessage
}
var file_db_vr_message_proto_depIdxs = []int32{
	0, // 0: vr.Request.ops:type_name -> vr.ShardOp
	1, // 1: vr.RequestMessage.req:type_name -> vr.Request
	2, // 2: vr.UnloggedRequestMessage.req:type_name -> vr.UnloggedRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_db_vr_message_proto_init() }
func file_db_vr_message_proto_init() {
	if File_db_vr_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_vr_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_vr_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_vr_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloggedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_vr_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_vr_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloggedRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_vr_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_vr_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_vr_message_proto_goTypes,
		DependencyIndexes: file_db_vr_message_proto_depIdxs,
		MessageInfos:      file_db_vr_message_proto_msgTypes,
	}.Build()
	File_db_vr_message_proto = out.File
	file_db_vr_message_proto_rawDesc = nil
	file_db_vr_message_proto_goTypes = nil
	file_db_vr_message_proto_depIdxs = nil
}
